# fly.toml file generated for app-rifa-frontend on 2023-01-06T10:37:27-03:00

app = "app-rifa-frontend"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "3000"
  REACT_APP_APP_NAME="Rifa Rifou App"
  REACT_APP_WEBSITE_DOMAIN="https://app-rifa-frontend.fly.dev:3000"
  REACT_APP_API_DOMAIN="https://withered-glitter-1351.fly.dev"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
