# fly.toml file generated for app-rifa-backend on 2023-01-04T22:12:04-03:00

app = "app-rifa-backend"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "3001"
  EMAIL_FROM_EMAIL = "contato@rifa.comofazer.net.br"
  EMAIL_FROM_NAME = "Equipe Técnica"
  EMAIL_HOST = "smtp.titan.email"
  EMAIL_PASSWORD = "WT6uRBPpn,V%u2|^"
  EMAIL_SEND_PORT = "465"
  EMAIL_USER_NAME = "contato@rifa.comofazer.net.br"
  SUPERTOKENS_APIKEY = "supertokens_is_awesome"
  SUPERTOKENS_API_DOMAIN = "https://withered-glitter-1351.fly.dev:3001"
  SUPERTOKENS_APP_NAME = "Rifa Rifou App"
  SUPERTOKENS_CONNECTION_URI = "https://withered-star-3436.fly.dev:3567"
  SUPERTOKENS_WEBSITE_DOMAIN = "https://localhost:3000"

[experimental]
  allowed_public_ports = [3001]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

[[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

[[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
