# fly.toml file generated for withered-star-3436 on 2023-01-04T19:46:10-03:00

app = "withered-star-3436"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "3567"
  POSTGRESQL_DATABASE_NAME = "neondb"
  POSTGRESQL_HOST = "ep-winter-cake-561539.cloud.neon.tech"
  POSTGRESQL_PASSWORD = "8e0LozuDRqsd"
  POSTGRESQL_PORT = "5432"
  POSTGRESQL_USER = "hugostudio"
  SKIP_PREFLIGHT_CHECK = "true"

[experimental]
  allowed_public_ports = [3567]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 3567
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 3567

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
